### ISSUE TITLE
Humanoid error

### ISSUE THREAD

**Issue by RyanAswegan** [Blugin/Humanoid-PMMP#1]
So whenever I create a humanoid, it creates it but its invisible. I try to add a skin to it and I cant because its not there. Am I placing it wrong or is there something else I need to do?
Thank You
Ryan Aswegan

**Comment by PresentKim** [comment]
I dont know why... 
Can you retry with last release?  https://github.com/PMMPPlugin/Humanoid/releases/tag/v1.0.4

**Comment by PresentKim** [comment]
I accidently closed this instead of the other problem.
